name: Merge blocklists
on:
  schedule:
    - cron: '0 */6 * * *' # every 6 hours
  workflow_dispatch:

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Fetch remote lists
        run: |
          mkdir -p tmp
          curl -fsSL "https://github.com/bigdargon/hostsVN/raw/master/hosts" -o tmp/hosts-vn.txt || true
          curl -fsSL "https://raw.githubusercontent.com/r-a-y/mobile-hosts/master/AdguardDNS.txt" -o tmp/adguard-dns.txt || true
          curl -fsSL "https://easylist.to/easylist/easyprivacy.txt" -o tmp/easyprivacy.txt || true
          curl -fsSL "https://a.rawtv.top/deny" -o tmp/deny.txt || true
          curl -fsSL "https://raw.githubusercontent.com/nextdns/click-tracking-domains/main/domains" -o tmp/allow-nextdns.txt || true
          curl -fsSL "https://raw.githubusercontent.com/AdguardTeam/HttpsExclusions/master/exclusions/banks.txt" -o tmp/allow-banks.txt || true
          curl -fsSL "https://a.rawtv.top/allow" -o tmp/allow-custom.txt || true

      - name: Normalize & build allow set
        run: |
          mkdir -p modes
          cat tmp/allow-nextdns.txt tmp/allow-banks.txt tmp/allow-custom.txt \
            | sed 's/^[0-9.]*[ \t]*//' \
            | sed 's/^[ \t]*//' \
            | tr '[:upper:]' '[:lower:]' \
            | grep -Eo '([a-z0-9._-]*[a-z0-9]\.[a-z]{2,})' \
            | sort -u > modes/allow.txt

      - name: Normalize & build block merged
        run: |
          cat tmp/hosts-vn.txt tmp/adguard-dns.txt tmp/easyprivacy.txt tmp/deny.txt \
            | sed 's/^[0-9.]*[ \t]*//' \
            | sed 's/^[ \t]*//' \
            | tr '[:upper:]' '[:lower:]' \
            | sed 's/#.*//' \
            | grep -Eo '([a-z0-9._-]*[a-z0-9]\.[a-z]{2,})' \
            | sort -u > modes/merged_block_all.txt

      - name: Create base (block minus allow)
        run: |
          comm -23 modes/merged_block_all.txt modes/allow.txt > modes/base.txt || cp modes/merged_block_all.txt modes/base.txt

      - name: Create yt and tt (append specific hosts)
        run: |
          cp modes/base.txt modes/yt.txt
          cp modes/base.txt modes/tt.txt
          # add youtube-specific hosts to yt
          echo "youtube.com" >> modes/yt.txt
          echo "ytimg.com" >> modes/yt.txt
          echo "googlevideo.com" >> modes/yt.txt
          sort -u modes/yt.txt -o modes/yt.txt
          # add tiktok-specific hosts to tt
          echo "tiktok.com" >> modes/tt.txt
          echo "tiktokcdn.com" >> modes/tt.txt
          echo "v16m.tiktokcdn.com" >> modes/tt.txt
          sort -u modes/tt.txt -o modes/tt.txt

      - name: Commit results
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add modes/*.txt || true
          git commit -m "Auto-update merged blocklists" || echo "no changes"
          git push || echo "push failed"
